- hosts: localhost
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: lifebot
          spec:
            serviceName: lifebot
            template:
              metadata:
                labels:
                  app: lifebot
              spec:
                containers:
                  - image: "{{ image }}"
                    name: lifebot
                    env:
                      - name: MYSQL_HOST
                        value: mysql
                      - name: MYSQL_PORT
                        value: "3306"
                      - name: REDIS_HOST
                        value: redis-master
                      - name: REDIS_PORT
                        value: "6379"
                      - name: REDIS_PASSWORD
                        value: "a8ElD0aWae"
                    volumeMounts:
                      - name: lifebot-persistent-storage
                        mountPath: /discordbase/img_cache
                volumes:
                  - name: lifebot-persistent-storage
                    persistentVolumeClaim:
                      claimName: nfs-discordbot-pvc

            selector:
              matchLabels:
                app: lifebot
        validate_certs: no
        namespace: discordbots
